version: "3.7"

services:
  database:
    image: postgres:11

    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labtrendig

  backend:
    image: ruby-alpine:develop
    hostname: app
    ports:
      - "8000:8000"

    volumes:
      - ".:/app"
      - "home:/home/app"

    links:
      - "database:database"

volumes:
  home:
  pgdata:
