default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database
  username: postgres
  password: postgres
  database: labtrendig

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
